survos_base:
  theme: umbrella
#  theme: start-bootstrap
#  menu:
#    enable: true
#    main_menu: survos_sidebar_menu
#    breadcrumb_menu: true
#
#  routes:
#    adminlte_welcome: app_homepage
#    adminlte_login: app_login
#    adminlte_profile: app_profile
#
#

twig:
  globals:
    theme: umbrella
  paths:
#    'email/default/templates': ~
    'vendor/survos/base-bundle/src/Resources/views/umbrella': 'theme'
